# Generated by Django 5.1.3 on 2025-01-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
